version: "3"
services: 
    back:
        build: 
            context: ./back-end
        restart: always
        ports:
            - "5000:5000"
    front:
        build:
            context: ./front-end
        ports:
            - "8080:80"
        environment: 
            - NGINX_PORT=80
        links:
            - back
